from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = 'profiles'
urlpatterns = [
    path('create-client-profile/',
         views.create_client_profile,
         name='create_client_profile'),
    path('edit-client-profile/<pk>/',
         views.edit_client_profile,
         name='edit_client_profile'),
    path('client-profile/<pk>/',
         views.view_client_profile,
         name='client_profile'),
    path('client-list/', views.view_client_list, name='client_list'),
    path('create-doctor-profile/',
         views.create_doctor_profile,
         name='create_doctor_profile'),
    path('edit-doctor-profile/<pk>/',
         views.edit_doctor_profile,
         name='edit_doctor_profile'),
    path('doctor-profile/<pk>/',
         views.view_doctor_profile,
         name='doctor_profile'),
    path('doctor-list/', views.view_doctor_list, name='doctor_list'),
    path('create-medication/',
         views.create_medication,
         name='create_medication'),
    path('edit-medication-profile/<pk>/',
         views.edit_medication_profile,
         name='edit_medication_profile'),
    path('medication-profile/<pk>/',
         views.view_medication_profile,
         name='medication_profile'),
    path('medication-list/', views.view_medication_list, name='medication_list'),
    path('create-prescription/',
         views.create_prescription,
         name='create_prescription'),
    path('edit-prescription-profile/<pk>/',
      views.edit_prescription_profile,
      name='edit_prescription_profile'),
    path('prescription-profile/<pk>/',
         views.view_prescription_profile,
         name='prescription_profile'),
    path('create-new-bodyweight/<client_id>',
      views.create_new_bodyweight,
      name='create_new_bodyweight'),
      path('bodyweight-list/<client_id>', views.view_bodyweight_list, name='bodyweight_list'),
]
urlpatterns += staticfiles_urlpatterns()
