# Generated by Django 3.2.5 on 2021-09-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('portrait', models.ImageField(default='images/default.jpeg', upload_to='images')),
                ('dob', models.DateField()),
                ('admission_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('current_client', models.BooleanField(default=True)),
            ],
        ),
    ]
