# Generated by Django 3.2.5 on 2021-09-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='doctors',
            field=models.ManyToManyField(to='profiles.Doctor'),
        ),
    ]
