# Generated by Django 3.2.5 on 2021-09-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210922_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_client',
            field=models.BooleanField(default=True),
        ),
    ]
