# Generated by Django 3.2.5 on 2021-09-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_client_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='profiles.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='suffix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_instructions', models.TextField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.medication')),
                ('prescribed_to', models.ManyToManyField(blank=True, to='profiles.Client')),
                ('prescribing_dr', models.ManyToManyField(blank=True, to='profiles.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='prescriptions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='profiles.prescription'),
            preserve_default=False,
        ),
    ]
