# Generated by Django 3.2.5 on 2021-09-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210923_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='prescriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.prescription'),
        ),
    ]
