# Generated by Django 3.2.5 on 2021-10-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210928_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uci_number',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
